version: '3.8'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
  mongodb:
    image: "mongo"
    container_name: mongodb
    env_file:
      - .env
    ports:
      - "27888:27017"


